// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIKvr0yGZf6FvmVAaPVFqLTvfEAKGP3E',
    appId: '1:344777508873:android:5c04d6ccd2b2d66411d0d8',
    messagingSenderId: '344777508873',
    projectId: 'pawtech-7bb7e',
    databaseURL: 'https://pawtech-7bb7e-default-rtdb.firebaseio.com',
    storageBucket: 'pawtech-7bb7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrhqzUrK-TcJGZCdc91dbGTjUd-F5ycmo',
    appId: '1:344777508873:ios:de89dd6efa43005211d0d8',
    messagingSenderId: '344777508873',
    projectId: 'pawtech-7bb7e',
    databaseURL: 'https://pawtech-7bb7e-default-rtdb.firebaseio.com',
    storageBucket: 'pawtech-7bb7e.firebasestorage.app',
    iosClientId: '344777508873-te7h2qmq09fa3ms1rvi9sqeuamv296pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawtech',
  );
}
